## <center> **Medical Insurance Cost Prediction** </center>
---

### <center> **Data Loading and Previewing** </center>

### Imports

In [121]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

import joblib
import json

### Load the data

In [51]:
df = pd.read_csv("insurance.csv")

### First five rows

In [52]:
df.head()

    age     sex     bmi  children smoker     region      charges
0  19.0  female  27.900         0    yes  southwest  16884.92400
1  18.0    male  33.770         1     no  southeast   1725.55230
2  28.0    male  33.000         3     no  southeast   4449.46200
3  33.0    male  22.705         0     no  northwest  21984.47061
4  32.0    male  28.880         0     no  northwest   3866.85520

### Last five rows

In [53]:
df.tail()

       age     sex    bmi  children smoker     region     charges
1333  50.0    male  30.97         3     no  northwest  10600.5483
1334  18.0  female  31.92         0     no  northeast   2205.9808
1335  18.0  female  36.85         0     no  southeast   1629.8335
1336  21.0  female  25.80         0     no  southwest   2007.9450
1337  61.0  female  29.07         0    yes  northwest  29141.3603

### Random five rows

In [54]:
df.sample(5)

       age   sex     bmi  children smoker     region      charges
851   61.0  male  32.300         2     no  northwest  14119.62000
451   30.0  male  24.130         1     no  northwest   4032.24070
986   43.0  male  30.115         3     no  northwest   8410.04685
1146  60.0  male  32.800         0    yes  southwest  52590.82939
77    21.0  male  35.530         0     no  southeast   1532.46970

### Number of rows and columns

In [55]:
df.shape

(1338, 7)

### Categorical columns

In [ ]:
categorical_cols = df.select_dtypes(include=["object"])
for column in categorical_cols:
    print(f"- {column}")

### Numeric columns

In [ ]:
numeric_cols = df.select_dtypes(include=["number"])

for column in numeric_cols:
    print(f"- {column}")

### Columns, datatypes and Indexrange

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1336 non-null   float64
 1   sex       1337 non-null   object
 2   bmi       1336 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1337 non-null   object
 5   region    1336 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(3), int64(1), object(3)
memory usage: 73.3+ KB

### Statistical summary

In [57]:
df.describe()

               age          bmi     children       charges
count  1336.000000  1336.000000  1338.000000   1338.000000
mean     39.225299    30.653447     1.094918  13270.422265
std      14.048210     6.096546     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.272500     0.000000   4740.287150
50%      39.000000    30.380000     1.000000   9382.033000
75%      51.000000    34.618750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

### Null values

In [58]:
df.isnull().sum()

age         2
sex         1
bmi         2
children    0
smoker      1
region      2
charges     0
dtype: int64

### <center> **Data Visualization** <center>
---

### Charges based on Sex

In [ ]:
sns.barplot(
    x= df["sex"],
    y= df["charges"],
    width=0.7
)

plt.show()

### Charges based on Smoking status

In [ ]:
sns.barplot(
    x= df["smoker"],
    y= df["charges"],
    width=0.7
)

plt.show()

### Percentage of charges based on Gender

In [ ]:
charges_percentage_gender = df.groupby("sex")["charges"].sum()

plt.pie(
    x= charges_percentage_gender.values,
    labels= charges_percentage_gender.index,
    autopct="%.2f%%"
)

plt.show()

### Charges based on Region

In [ ]:
sns.barplot(
    x= df["region"],
    y= df["charges"],
    palette="viridis"
)

plt.show()

### Percentage of charges based on Smoking status

In [ ]:
charges_percentage_smoking = df.groupby("smoker")["charges"].sum()

plt.pie(
    x= charges_percentage_smoking.values,
    labels= charges_percentage_smoking.index,
    autopct="%.2f%%"
)
plt.show()

### Charges based on Children

In [ ]:
sns.lineplot(
    x= df["children"],
    y= df["charges"],
    color="purple"
)

plt.show()

### Percentage of charges based on Region

In [ ]:
charges_percentage_region = df.groupby("region")["charges"].sum()
plt.pie(
    x= charges_percentage_region.values,
    labels= charges_percentage_region.index,
    autopct="%.2f%%"
)

plt.show()

### Charges based on BMI

In [ ]:
sns.lineplot(
    x= df["charges"],
    y= df["bmi"],
    color="blue"
)

plt.show()

### Charges based on Age

In [ ]:
sns.lineplot(
    x= df["age"],
    y= df["charges"],
    color="yellow"
)
plt.show()

### <center> **Data Preprocessing and Model Training** </center>
---

### Features and Target

In [59]:
X = df.drop("charges", axis=1)
y = df["charges"]

### Training and Test sets

In [77]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [61]:
df.head()

    age     sex     bmi  children smoker     region      charges
0  19.0  female  27.900         0    yes  southwest  16884.92400
1  18.0    male  33.770         1     no  southeast   1725.55230
2  28.0    male  33.000         3     no  southeast   4449.46200
3  33.0    male  22.705         0     no  northwest  21984.47061
4  32.0    male  28.880         0     no  northwest   3866.85520

### Separate Categorical and Numeric columns

In [78]:
numerical_features = [
    "age",
    "bmi",
    "children",
]

categorical_features = [
    "sex",
    "smoker",
    "region"
]

### Build preprocessing pipeline

In [79]:
numeric_transformer = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(
                strategy="median"
            )
        )
    ]
)

categorical_transformer = Pipeline(
    steps= [
        (
            "imputer",
            SimpleImputer(
                strategy="most_frequent"
            )
        ),
        (
            "encoder",
            OneHotEncoder(
                handle_unknown="ignore"
            )
        )
    ]
)

### Column Transformer

In [80]:
preprocessor = ColumnTransformer(
    transformers= [
        (
            "num",
            numeric_transformer,
            numerical_features
        ),
        (
            "cat",
            categorical_transformer,
            categorical_features
        )
    ]
)

### Create Decision Tree pipeline

In [108]:
pipeline = Pipeline(
    steps= [
        (
            "preprocessor",
            preprocessor
        ),
        (
            "classifier",
            RandomForestRegressor(
                random_state=42
            )
        )
    ]
)

### Train Model

In [109]:
model = pipeline.fit(X_train, y_train)

### Make Predictions

In [110]:
y_test_pred = model.predict(X_test)
y_train_pred = model.predict(X_train)
print(y_test_pred)

[ 9635.226465   6030.1933399 28325.8993115 12372.0766665 34740.4070437
  8336.2078785  2136.871807  14715.8631332  6061.0045165 11053.7967965
 19181.6831886  6910.9485555  4487.5573374 46270.3461023 48699.8381584
 45235.8860253 10573.67084   43612.5430069 10221.2925575 24878.1053248
  6161.0907474  8742.6061206  1539.320941   2625.1003675 12583.0844128
 12773.5121524 14599.8965965  5164.9636894 10648.4522581  3802.0210271
  7697.499577  11716.3700655  2973.350004   6246.4387752  3590.3633826
 11986.4843113  4304.5254491  7866.2570474 23885.5140495  5580.7406058
  7277.2255223  2726.5197003 14969.7173226 13864.1641362  6280.496138
 16154.3975256 18206.4702394  7204.5158697 41858.7112164  6416.5069549
 13978.466564   2267.475323   6351.8253884  2029.0496134 11584.8541422
 11135.4193488  3740.3440642 46055.8064045 11876.7701435 15543.5649466
 13789.1457305  7662.1073234 21401.4130523  7395.7813065 12885.1219812
  6334.2436594 18044.0645418 12868.974878   6738.4720346  1978.6844525
  7102.7467238 10270.7442876  9670.735637  12126.1861198  8908.5024716
  5366.8370588  7688.0760847 12594.0613548  4460.5863531  9024.9861066
  2480.2721536 27977.3090911  6169.999605  37821.7514215 40706.687304
 41756.969258   5971.5024677 11452.2308319  9567.6141328 14858.3604991
 19363.0343076 26800.664739  27565.7061799  5273.8092314 45507.5880837
  7125.8332648 20232.1108368  3570.8563781 17977.6105966  6414.9277951
  5861.8029333  1742.3025515  6910.4408957 17413.3581085 13638.867682
  6136.9444795 10041.779838  24227.935143   1711.0257335 24003.1541935
  1390.258835   3424.7447308 12801.2861574 41180.8049855 12172.0582568
  7303.7648018 12647.34142   24644.6639103  8717.4527567  6559.7665658
  6248.7302826  8636.8267282 16743.738585   2353.6664213  6955.0546003
  7558.0641085 11324.3464951 10260.2551708 16254.7155412  2321.5763419
  3983.317318   6816.6267469  6204.4216121 11957.5641027  5772.6841605
 23417.693232   6087.2031044 35008.1268413 46023.910445  38990.827794
  5257.4979506 14304.6142129  3000.1259833 17441.6177462  2641.3683279
 24220.1542367  6516.4921135  5946.9105081 13209.6653814  4987.55501
 51019.2566218  6146.3126292  1272.0232285 45927.5121828  6452.5519367
  4521.4436761 13522.397815  10171.9672261 35805.1363366 39696.4042475
 14852.2064728  3088.810101  21018.7596218  4682.0153713  5734.2793844
  9067.7089477 48322.1564411 44913.2607912 40579.9108756  7750.8620938
 11325.6307888  6571.0153201  6296.3700092  4714.5094076  3156.4528794
 24967.1121129 16890.8189285 14235.1607691 16968.1083286 12037.7102649
 27964.3550449  7824.0916804 10206.0204224  5623.7432636  6175.5968333
  5502.586468   5049.4037389  6498.6062528  8786.6388249 12683.0605395
  4680.8405887  6730.3068525  3150.9170772 48814.3215212 13237.9155183
  9498.648969   3135.940737  17192.011337   3624.658739  12550.8073532
  3726.8070858 24402.7431428  9057.4581323  5333.7467345 19500.4273529
 19529.2730254 12587.3679323 11434.3335492 10423.5427067  5786.6627137
 13738.9304848 13498.8102417 11273.9499089 19395.2810745  8528.9582329
  4258.3205104  4722.216827  14940.1593472 15841.9163778  5444.1793958
  2552.7087972 10337.3745142 10572.1277045 44917.4197273  1975.1338885
 38801.4876554  1731.6219205  1657.5455635 10018.4861641 11665.7381689
  2803.1488796  9602.3113745  7110.9774163 25849.4128759  9762.075322
 11029.7606127  4273.5857843  7376.1306786 44639.6274523  3520.5891652
 14020.4684409 40473.026953   3934.846486   3764.7953182  1661.4328155
  4329.4432312  4763.9659069  4383.085459  14810.7394875  2255.2841392
  2362.31651    8203.4939349  4328.4648658 11980.353186   3129.752159
  4012.8401121 12740.627743   7226.5384578  9981.5902743  6460.5991383
  7616.114589  15054.9251627 19910.88078   46898.1814741 12598.3110379
  6524.3046169 47314.1691052  9886.7229185  9416.8083582 14269.5612979
 10722.8534868 11359.8638795 12482.5511252 14160.7611973  2758.9069339
 13898.0314858  8001.2506848 39724.242148   5848.4396273  9781.9618349
 10079.3379019 14427.2908528 13091.405734   9891.8612481 39921.4712235
  2931.0788203 10069.1951997 48887.0690714  5377.0396913  5394.9651343
  2985.723853  11172.7151805 15652.74855   13428.8302267 11341.8725813
 14459.6958534 10569.9629555  4585.6628081  2405.3256361 39626.992091
 39776.3601164 11744.422234   9627.1475502 16757.3112557 14582.9612925
 40336.2422104  3827.8226331 47525.5246269  7537.2009969  1747.927869
  6268.319632   2709.7881555 17863.9029751 13546.255979   3212.9495622
 15822.3034615 11643.0565974 12810.2480413 41742.3347647 12756.124108
 25418.2525043  7815.138117  16514.5872984  5640.8497958 11432.2124495
  9050.4068487 15332.0318946 17039.9265717  3490.2198454 11716.0413972
 13724.792509  12816.9038375  4936.9789197 33855.2944145  6696.3437709
  5164.5610845  4939.3854734  9681.8867231 42487.2856341 10743.8399729
 17070.2434156  7304.1571764  6589.7500229  5494.091853  14834.462744
  9029.6801888  6198.7428713  2093.6120345 10728.0879    12823.7830037
  5307.3969522  4296.2000915 12912.4612967  4069.9696134 41707.3626175
 37504.9890505 46890.0406825  8167.4737819 10795.3144281  6318.6428941
  2865.169647  22330.3745441  7456.2837419 18514.5490327 43737.206289
  5415.1187805 13645.4993456  6547.3431176 10137.1266401 13591.6302536
 21125.1761826 12260.2015361  7812.7840465  7607.1355486  3770.7349488
 11620.5842925 20653.6019363 11937.0652722  9771.8262446  4199.4673656
 11183.891011   6252.3850085 10838.0671767  9442.9375416 24215.883443
 48984.5125915 11789.9444735  9858.5070984 13764.5896227 14264.7443163
  6725.1477261  5552.4004549  7653.003785   4866.7139489 11317.9921316
  5248.4737141 12175.906285  14361.3146458  4854.5320452  6226.4914872
 12985.8874115  3581.1039137]

### Campare results

In [111]:
# Combine actual and predicted values side by side
results = np.column_stack((y_test, y_test_pred))

# Printing the results
print("Actual Values  |  Predicted Values")
print("-----------------------------")
for actual, predicted in results:
    print(f"{actual:14.2f} |  {predicted:12.2f}")

Actual Values  |  Predicted Values
-----------------------------
       9095.07 |       9635.23
       5272.18 |       6030.19
      29330.98 |      28325.90
       9301.89 |      12372.08
      33750.29 |      34740.41
       4536.26 |       8336.21
       2117.34 |       2136.87
      14210.54 |      14715.86
       3732.63 |       6061.00
      10264.44 |      11053.80
      18259.22 |      19181.68
       7256.72 |       6910.95
       3947.41 |       4487.56
      46151.12 |      46270.35
      48673.56 |      48699.84
      44202.65 |      45235.89
       9800.89 |      10573.67
      42969.85 |      43612.54
       8233.10 |      10221.29
      21774.32 |      24878.11
       5080.10 |       6161.09
       7441.50 |       8742.61
       1256.30 |       1539.32
       2755.02 |       2625.10
      11085.59 |      12583.08
      10923.93 |      12773.51
      12644.59 |      14599.90
      18804.75 |       5164.96
       9715.84 |      10648.45
       1131.51 |       3802.02
      15828.82 |       7697.50
      11842.62 |      11716.37
       2020.55 |       2973.35
       5693.43 |       6246.44
       2904.09 |       3590.36
       7448.40 |      11986.48
       2597.78 |       4304.53
       7337.75 |       7866.26
      23887.66 |      23885.51
      38709.18 |       5580.74
       4687.80 |       7277.23
       2643.27 |       2726.52
      11674.13 |      14969.72
      12124.99 |      13864.16
       4890.00 |       6280.50
      12333.83 |      16154.40
       3579.83 |      18206.47
       4391.65 |       7204.52
      42124.52 |      41858.71
       4463.21 |       6416.51
      13887.20 |      13978.47
       1719.44 |       2267.48
      28476.73 |       6351.83
       1708.93 |       2029.05
      10594.23 |      11584.85
      25333.33 |      11135.42
       3645.09 |       3740.34
      38746.36 |      46055.81
      11848.14 |      11876.77
      10564.88 |      15543.56
      13880.95 |      13789.15
       4753.64 |       7662.11
      27941.29 |      21401.41
       8017.06 |       7395.78
      23045.57 |      12885.12
       4133.64 |       6334.24
      17942.11 |      18044.06
      25992.82 |      12868.97
       3594.17 |       6738.47
       1682.60 |       1978.68
       6079.67 |       7102.75
       9411.00 |      10270.74
       8283.68 |       9670.74
       6338.08 |      12126.19
       7152.67 |       8908.50
       4889.04 |       5366.84
       4846.92 |       7688.08
      11454.02 |      12594.06
       4349.46 |       4460.59
       9101.80 |       9024.99
       1391.53 |       2480.27
      28101.33 |      27977.31
       5152.13 |       6170.00
      38511.63 |      37821.75
      44501.40 |      40706.69
      41097.16 |      41756.97
       4837.58 |       5971.50
      10601.63 |      11452.23
       8310.84 |       9567.61
      11264.54 |      14858.36
      15230.32 |      19363.03
      27037.91 |      26800.66
      23401.31 |      27565.71
       5031.27 |       5273.81
      38282.75 |      45507.59
       6875.96 |       7125.83
      19719.69 |      20232.11
       1880.07 |       3570.86
      18765.88 |      17977.61
       6402.29 |       6414.93
       4527.18 |       5861.80
       1743.21 |       1742.30
       5709.16 |       6910.44
      12363.55 |      17413.36
      13129.60 |      13638.87
       1727.54 |       6136.94
       7731.43 |      10041.78
      21195.82 |      24227.94
       1702.46 |       1711.03
      23244.79 |      24003.15
      23082.96 |       1390.26
       2927.06 |       3424.74
      13019.16 |      12801.29
      37701.88 |      41180.80
       9778.35 |      12172.06
       1980.07 |       7303.76
      30260.00 |      12647.34
      22478.60 |      24644.66
       6313.76 |       8717.45
       2789.06 |       6559.77
       5594.85 |       6248.73
       7261.74 |       8636.83
      11396.90 |      16743.74
       1986.93 |       2353.67
       4719.74 |       6955.05
       7749.16 |       7558.06
       7345.73 |      11324.35
       9288.03 |      10260.26
      12244.53 |      16254.72
       1837.28 |       2321.58
       3972.92 |       3983.32
       5934.38 |       6816.63
       5836.52 |       6204.42
       7935.29 |      11957.56
       5649.72 |       5772.68
      12347.17 |      23417.69
      12404.88 |       6087.20
      22144.03 |      35008.13
      42983.46 |      46023.91
      37270.15 |      38990.83
       5267.82 |       5257.50
       9866.30 |      14304.61
       2322.62 |       3000.13
      33471.97 |      17441.62
       2137.65 |       2641.37
      23306.55 |      24220.15
       5261.47 |       6516.49
       3761.29 |       5946.91
      11436.74 |      13209.67
       4751.07 |       4987.56
      46661.44 |      51019.26
       2690.11 |       6146.31
       1146.80 |       1272.02
      37607.53 |      45927.51
       6373.56 |       6452.55
       4518.83 |       4521.44
      13555.00 |      13522.40
       8547.69 |      10171.97
      34439.86 |      35805.14
      39125.33 |      39696.40
      13607.37 |      14852.21
       2710.83 |       3088.81
      14988.43 |      21018.76
       2396.10 |       4682.02
       3591.48 |       5734.28
       7162.01 |       9067.71
      48824.45 |      48322.16
      43578.94 |      44913.26
      39556.49 |      40579.91
       2632.99 |       7750.86
       9182.17 |      11325.63
       6238.30 |       6571.02
       5757.41 |       6296.37
       4239.89 |       4714.51
       2154.36 |       3156.45
      21978.68 |      24967.11
      16297.85 |      16890.82
      13831.12 |      14235.16
      32734.19 |      16968.11
      11830.61 |      12037.71
      29523.17 |      27964.36
       3167.46 |       7824.09
       8428.07 |      10206.02
       5012.47 |       5623.74
       5209.58 |       6175.60
       2855.44 |       5502.59
      20277.81 |       5049.40
       3554.20 |       6498.61
       8569.86 |       8786.64
      10594.50 |      12683.06
       3597.60 |       4680.84
       7323.73 |       6730.31
       2731.91 |       3150.92
      38711.00 |      48814.32
      12981.35 |      13237.92
       9283.56 |       9498.65
       2709.11 |       3135.94
      12096.65 |      17192.01
       2198.19 |       3624.66
       8932.08 |      12550.81
       3176.29 |       3726.81
      24393.62 |      24402.74
       4266.17 |       9057.46
      22493.66 |       5333.75
      17085.27 |      19500.43
      16577.78 |      19529.27
       8827.21 |      12587.37
       4296.27 |      11434.33
       7804.16 |      10423.54
       3208.79 |       5786.66
      12957.12 |      13738.93
      22192.44 |      13498.81
       9432.93 |      11273.95
      17043.34 |      19395.28
       6593.51 |       8528.96
       4137.52 |       4258.32
       4779.60 |       4722.22
      14001.29 |      14940.16
      12629.90 |      15841.92
       5245.23 |       5444.18
       2404.73 |       2552.71
       6948.70 |      10337.37
       6435.62 |      10572.13
      42560.43 |      44917.42
       2055.32 |       1975.13
      34672.15 |      38801.49
       1731.68 |       1731.62
       1639.56 |       1657.55
       9377.90 |      10018.49
      10977.21 |      11665.74
       1534.30 |       2803.15
       9644.25 |       9602.31
       4529.48 |       7110.98
      37829.72 |      25849.41
       9991.04 |       9762.08
       8125.78 |      11029.76
       3877.30 |       4273.59
       5979.73 |       7376.13
      43896.38 |      44639.63
       1674.63 |       3520.59
      13204.29 |      14020.47
      44585.46 |      40473.03
       3021.81 |       3934.85
       3392.98 |       3764.80
       1632.04 |       1661.43
       2699.57 |       4329.44
      20177.67 |       4763.97
       4076.50 |       4383.09
      12592.53 |      14810.74
       1621.34 |       2255.28
       1875.34 |       2362.32
       7196.87 |       8203.49
       3161.45 |       4328.46
      12029.29 |      11980.35
       2719.28 |       3129.75
      18218.16 |       4012.84
      12146.97 |      12740.63
       3292.53 |       7226.54
       8688.86 |       9981.59
       6113.23 |       6460.60
       8059.68 |       7616.11
      13415.04 |      15054.93
      18246.50 |      19910.88
      47055.53 |      46898.18
      12222.90 |      12598.31
       6067.13 |       6524.30
      63770.43 |      47314.17
       9872.70 |       9886.72
       9193.84 |       9416.81
       8534.67 |      14269.56
      27117.99 |      10722.85
       8596.83 |      11359.86
      12475.35 |      12482.55
      13405.39 |      14160.76
       2150.47 |       2758.91
      13747.87 |      13898.03
       6610.11 |       8001.25
      39047.29 |      39724.24
      27375.90 |       5848.44
       9048.03 |       9781.96
       8988.16 |      10079.34
      14901.52 |      14427.29
      10096.97 |      13091.41
       8835.26 |       9891.86
      38415.47 |      39921.47
       2721.32 |       2931.08
       9877.61 |      10069.20
      47269.85 |      48887.07
       4237.13 |       5377.04
       2534.39 |       5394.97
       2205.98 |       2985.72
      10965.45 |      11172.72
      15006.58 |      15652.75
      10736.87 |      13428.83
       9788.87 |      11341.87
      10422.92 |      14459.70
       9304.70 |      10569.96
       3378.91 |       4585.66
       2155.68 |       2405.33
      38126.25 |      39626.99
      35491.64 |      39776.36
       6356.27 |      11744.42
      24059.68 |       9627.15
      16450.89 |      16757.31
      12925.89 |      14582.96
      36950.26 |      40336.24
       2459.72 |       3827.82
      46889.26 |      47525.52
       5124.19 |       7537.20
      14133.04 |       1747.93
       6414.18 |       6268.32
       1720.35 |       2709.79
      15817.99 |      17863.90
      13462.52 |      13546.26
       2103.08 |       3212.95
      12105.32 |      15822.30
      20781.49 |      11643.06
      12235.84 |      12810.25
      41949.24 |      41742.33
      12643.38 |      12756.12
      21223.68 |      25418.25
       7954.52 |       7815.14
      15170.07 |      16514.59
       3659.35 |       5640.85
       8232.64 |      11432.21
       8027.97 |       9050.41
      13919.82 |      15332.03
      10791.96 |      17039.93
      17878.90 |       3490.22
      10601.41 |      11716.04
      13217.09 |      13724.79
      11944.59 |      12816.90
      14358.36 |       4936.98
      32548.34 |      33855.29
       5699.84 |       6696.34
       2352.97 |       5164.56
       4340.44 |       4939.39
       9391.35 |       9681.89
      42211.14 |      42487.29
       8823.28 |      10743.84
      14256.19 |      17070.24
       7133.90 |       7304.16
       5312.17 |       6589.75
       3906.13 |       5494.09
       2203.47 |      14834.46
      28340.19 |       9029.68
       5484.47 |       6198.74
       1622.19 |       2093.61
      11299.34 |      10728.09
       8026.67 |      12823.78
      11737.85 |       5307.40
       2913.57 |       4296.20
       9861.02 |      12912.46
       2473.33 |       4069.97
      39983.43 |      41707.36
      36307.80 |      37504.99
      44400.41 |      46890.04
       3172.02 |       8167.47
       7742.11 |      10795.31
       6185.32 |       6318.64
       1880.49 |       2865.17
      21771.34 |      22330.37
       6858.48 |       7456.28
      17179.52 |      18514.55
      42760.50 |      43737.21
       5478.04 |       5415.12
      12638.19 |      13645.50
       5989.52 |       6547.34
       9566.99 |      10137.13
      10370.91 |      13591.63
      19594.81 |      21125.18
      11576.13 |      12260.20
       6360.99 |       7812.78
       4032.24 |       7607.14
       2585.27 |       3770.73
      11658.38 |      11620.58
      21082.16 |      20653.60
      10807.49 |      11937.07
       9724.53 |       9771.83
       3201.25 |       4199.47
       3309.79 |      11183.89
       5969.72 |       6252.39
       8269.04 |      10838.07
       9414.92 |       9442.94
      23967.38 |      24215.88
      47928.03 |      48984.51
      11842.44 |      11789.94
       7421.19 |       9858.51
      12950.07 |      13764.59
      11033.66 |      14264.74
       6082.40 |       6725.15
       3989.84 |       5552.40
       7537.16 |       7653.00
       3484.33 |       4866.71
       8116.68 |      11317.99
      17626.24 |       5248.47
      11837.16 |      12175.91
       9541.70 |      14361.31
       4399.73 |       4854.53
       2200.83 |       6226.49
      11363.28 |      12985.89
       1964.78 |       3581.10

### Evalaute results

In [112]:
train_mse = mean_squared_error(y_train_pred, y_train)
test_mse = mean_squared_error(y_test_pred, y_test)

train_mae = mean_absolute_error(y_train_pred, y_train)
test_mae = mean_absolute_error(y_test_pred, y_test)

train_r2 = r2_score(y_train_pred, y_train)
test_r2 = r2_score(y_test_pred, y_test)

print(f"\nTrain MSE: {train_mae}")
print(f"Test MSE: {test_mae}\n")

print(f"\nTrain MAE: {train_mae}")
print(f"Test MAE: {test_mae}\n")

print(f"\nTrain R2: {train_r2}")
print(f"Test R2: {test_r2}")

Train MSE: 1043.701329566881
Test MSE: 2666.369257433831


Train MAE: 1043.701329566881
Test MAE: 2666.369257433831


Train R2: 0.9748431882491034
Test R2: 0.8243777254102329

### Save Model

In [122]:
joblib.dump(model, "delivery_time_model.pkl")

metadata = {
    "categorical_options": {
        col: sorted(df[col].dropna().unique().tolist())
        for col in ['sex', 'smoker', 'region']
    },
    "numeric_ranges": {
        "age": [float(df["age"].min()), float(df["age"].max())],
        "bmi": [float(df["bmi"].min()), float(df["bmi"].max())],
        "children": [float(df["children"].min()), float(df["children"].max())],
    }
}

with open("model_metadata.json", "w") as f:
    json.dump(metadata, f, indent=2)